### ISSUE TITLE
Write setup guide

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-actionscript3-tracker#10]
I've temporarily activated the wiki and created this page:

https://github.com/snowplow/snowplow-actionscript3-tracker/wiki/ActionScript3-Tracker-Setup

Once written, we will move the page over to here:

https://github.com/snowplow/snowplow/wiki/ActionScript3-Tracker-Setup

(We're doing it this way because forking wiki repos is very fiddly.)

**Comment by ephraimtabackman** [comment]
I want to link to a compiled binary (.swc) file for the AS3 tracker.

What is the correct location for the storage of stable, nightly, etc. builds?

**Comment by alexanderdean** [comment]
Hey @ephraimtabackman - good question! I have gone ahead and created a Bintray home for the binary: https://bintray.com/snowplow/snowplow-generic/snowplow-actionscript3-tracker/0.1.0/view

Normally we zip things before storing them and turn -s to _s in the zipfile name. So the download link would be:

    http://dl.bintray.com/snowplow/snowplow-generic/snowplow_actionscript3_tracker_0.1.0.zip

Does that sound good?

**Comment by ephraimtabackman** [comment]
Thanks. How do I put the binary file there?

**Comment by alexanderdean** [comment]
Can you email it to me? I don't think Bintray supports package-level
perms...

On Wed, Jan 21, 2015 at 3:05 PM, Ephraim Tabackman <notifications@github.com
> wrote:

> Thanks. How do I put the binary file there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-actionscript3-tracker/issues/10#issuecomment-70852823>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7881 622 925
@alexcrdean <https://twitter.com/alexcrdean>

**Comment by ephraimtabackman** [comment]
Ok. I will reference that URL for now in the docs, and when we have a good stable binary will email it to you. Thank you.

**Comment by alexanderdean** [comment]
Cheers Ephraim!

On Wed, Jan 21, 2015 at 3:08 PM, Ephraim Tabackman <notifications@github.com
> wrote:

> Ok. I will reference that URL for now in the docs, and when we have a good
> stable binary will email it to you. Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-actionscript3-tracker/issues/10#issuecomment-70853291>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7881 622 925
@alexcrdean <https://twitter.com/alexcrdean>

**Comment by alexanderdean** [comment]
This is done, closing
