### ISSUE TITLE
Confirm that structured event tracking works

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-actionscript3-tracker#14]
I can't see any structured events in either Redshift or the bad rows table!

**Comment by natilivni** [comment]
can you please reference some unit tests that generate structured events that we can port over?

**Comment by alexanderdean** [comment]
@fblundun could you add in a couple of links?

**Comment by fblundun** [comment]
Here's the relevant test in the Python Tracker: https://github.com/snowplow/snowplow-python-tracker/blob/master/snowplow_tracker/test/integration/test_integration.py#L131-L137

And the Ruby Tracker: https://github.com/snowplow/snowplow-ruby-tracker/blob/master/spec/integration/integration_spec.rb#L112-L127

And the Node.js Tracker: https://github.com/snowplow/snowplow-nodejs-tracker/blob/feature/0.2.0/tests/tracker.js#L111-L135

**Comment by alexanderdean** [comment]
Thanks Fred

**Comment by alexanderdean** [comment]
Done, closing
