### ISSUE TITLE
Is there any Flash-specific way for tracking users

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-actionscript3-tracker#15]
For users tracked via the Javascript tracker, we can track individual users across multiple events using the following fields:

* `domain_userid` (first party cookie)
* `user_fingerprint` (browser fingerprint)

The collector tracks IP address and sets a third party cookies, so these are also available for user tracking.

For tracking users on via the action script tracker, is there a Flash equivalent of first party cookies? Or do we fall back to using 3rd party cookies? (It would be a shame if we had to do this, as an increasing number of browsers block 3rd party cookies.)

**Comment by natilivni** [comment]
flash has its own storage.  It can also access javascript in most environments and can therefore access the browser cookie collection.  I suggest we try getting the javascript cookie from flash and only fall back to the flash storage.  That way, if a user has an environment where he is tracking using both the javascript and actionscript trackers, the users will be the same.  I was not able to find code that contains either "domain_userid" or "user_fingerprint" in the javascript traker.  Can you please point me to the code and I will rewrite it in actionscript?

**Comment by alexanderdean** [comment]
@fblundun - can you give Nati some links plus a para to how the domain_ cookies work in the JS Tracker?

Also - if we are going to fall back to Flash Storage, there is a question as to whether we put the IDs built/stored in Flash Storage in new fields (in flash_context), or whether we overload the existing domain_ fields... @yalisassoon do you have a view on this?

**Comment by yalisassoon** [comment]
As a rule we should never overload a field.

My preference would be to have two separate processes in the Flash tracker
- one that gets / sets the domain_userid via JS, as is done currently in
the JS tracker - using the `duid` field in the tracker protocol.

The second process would set a user and session id based on Flash storage,
and populate values in the Flash context JSON.

At analysis time we can then apply the logic that first uses the
domain_userid and falls back to Flash when that works. That way, we have
the flexibility to apply a different business logic - we may find, for
example, that users are more likely to delete their JS set cookies than
their Flash storage based cookies, or that there is some other reason why
these might be more reliable than the JS based approach. So it gives us
extra flexibility at analysis time, and hopefully simplifies the tracker
(because the two processes are independent).

On Tue, Jan 20, 2015 at 9:05 AM, Alexander Dean <notifications@github.com>
wrote:

> @fblundun <https://github.com/fblundun> - can you give Nati some links
> plus a para to how the domain_ cookies work in the JS Tracker?
>
> Also - if we are going to fall back to Flash Storage, there is a question
> as to whether we put the IDs built/stored in Flash Storage in new fields
> (in flash_context), or whether we overload the existing domain_ fields...
> @yalisassoon <https://github.com/yalisassoon> do you have a view on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-actionscript3-tracker/issues/15#issuecomment-70623507>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by alexanderdean** [comment]
Sounds great - @natilivni, @ephraimtabackman can you please add `userId` and `sessionIndex` to the `flash_context`? This is a patch so we can just override the 1-0-0 version...

**Comment by fblundun** [comment]
Hi @natilivni ,

Here's a link to the JS Tracker wiki page about our use of cookies: https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker#cookies

We use two cookies: an ID cookie and a session cookie. The session cookie simply differentiates between different sessions: if a user leaves and then returns before the session cookie has expired, the new visit won't count as a new session. The ID cookie contains information about the user and the current session, in this order:

* the user's domain_userid
* the timestamp for their first visit
* The number of times they have visited
* the timestamp for their current visit
* the timestamp for their last visit

This is the library we use to set and read cookies: https://github.com/litejs/browser-cookie-lite

This is where the ID cookie is loaded: https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L451-L491.

If the cookie doesn't yet exist, a random 16-character ID is generated for use in the future.

This is where the ID cookie and session cookie are actually saved: https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L543

The user fingerprint is created based on browser features such as which plugins are present using this function: https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/lib/detectors.js#L109-L139

And it's actually used here: https://github.com/snowplow/snowplow-javascript-tracker/blob/master/src/js/tracker.js#L183

Does that help?

**Comment by alexanderdean** [comment]
Thanks Fred!

**Comment by alexanderdean** [comment]
This has been implemented now, closing.
