### ISSUE TITLE
Send through link clicks events as unstructured events rather than custom contexts

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-actionscript3-tracker#17]
Currently link_click event jsons are sent in as part of the contexts array e.g.

```json
{
    "schema": "iglu:com.snowplowanalytics.snowplow/contexts/jsonschema/1-0-0",
    "data": [
        {
            "schema": "iglu:com.snowplowanalytics.snowplow/link_click/jsonschema/1-0-1",
            "data": {
                "targetUrl": "http://www.google.com"
            }
        },
        {
            "schema": "iglu:com.snowplowanalytics.snowplow/flash_context/jsonschema/1-0-0",
            "data": {
                "hasLocalStorage": true,
                "stageSize": {
                    "height": 893,
                    "width": 1131
                },
                "version": "WIN 11,1,102,63",
                "isDebugger": true,
                "playerType": "ActiveX",
                "hasScriptAccess": true
            }
        }
    ]
}
```

These should instead be sent in as an unstructured event. This means moving the JSON out of the contexts array and passing it in as a separate `ue_px` or `ur_pr` parameter (depending on whether it is base64 or url encoded)

**Comment by natilivni** [comment]
I used that in order to move away from the fake example schema that was ported over from the java tracker tests.  What would you recommend as a small and simple schema to use as a context for the tests?

**Comment by alexanderdean** [comment]
This one is not too bad, it's all mostly optional JSON numbers: https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/geolocation_context/jsonschema/1-0-0
