### ISSUE TITLE
Flash security support - crossdomain.xml

### ISSUE THREAD

**Issue by natilivni** [snowplow/snowplow-actionscript3-tracker#19]
When in a live environment, flash becomes subject to certain security restrictions.  (see here: http://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118a9b90204-7e3f.html).  Security is managed by placing a crossdomain.xml file on the root of the host to which the flash movie is trying to make a request.  The most permisive crossdomain policy looks like this:

<?xml version="1.0"?>
<cross-domain-policy>
  <allow-access-from domain="*" secure="false" />
</cross-domain-policy>

We need such a file hosted on http://astracker.snplow.com/crossdomain.xml so that we can run the flash movie in the real world.

**Comment by alexanderdean** [comment]
Hey @natilivni - interesting. Are you saying that the Snowplow event collector needs a file hosted, similar to how we are working on CORS support for the JS Tracker?

**Comment by natilivni** [comment]
Yes, as long as you are running the flash movie as a developer, (eg. it is being opened on the browser through the file system and not through http, you can access any domain.  If you are hosted, then you need permission to access any subdomain other than the one your movie is hosted on.

**Comment by alexanderdean** [comment]
Right - is this POST specific, or relates to GETs too?

**Comment by natilivni** [comment]
Its the same for all requests, GETS and POSTS

**Comment by natilivni** [comment]
Here is the specification for the crossdomain.xml file: http://www.adobe.com/devnet/articles/crossdomain_policy_file_spec.html

**Comment by alexanderdean** [comment]
Okay cool, I've scheduled this as tickets in the relevant project (snowplow/snowplow)...

**Comment by natilivni** [comment]
Great! Thanks!
