### ISSUE TITLE
Fix domainUserId storage in cookies and Flash storage

### ISSUE THREAD

**Issue by nakulgan** [snowplow/snowplow-actionscript3-tracker#46]
domainUserId stored using LocalStorage (cookie/sharedObject) is read with incorrect namespace.  

A domainUserId is created for each payload and the storage is updated, the next payload does the same because, it reads from the LocalStorage in a different namespace resulting a null value. Each payload therefore has a unique domainUserId.   

Instances of LocalStorage in tracker use `this.configStorageNamePrefix + baseName + '.' + this.{cookieDomainHash/sharedObjectDomainHash}` as key in setter, and use key `id` in getter.

[Get](https://github.com/snowplow/snowplow-actionscript3-tracker/blob/master/snowplow-as3-tracker/src/com/snowplowanalytics/snowplow/tracker/Tracker.as#L630)  and [Set](https://github.com/snowplow/snowplow-actionscript3-tracker/blob/master/snowplow-as3-tracker/src/com/snowplowanalytics/snowplow/tracker/Tracker.as#L605)

**Comment by alexanderdean** [comment]
Hey @nakulgan - thanks for catching this. Could you re-phrase the description a bit to make the exact bug clear? I've read it a couple of times and I don't quite follow.

**Comment by alexanderdean** [comment]
Updated ticket name, please note for the commit

**Comment by alexanderdean** [comment]
De-scheduling as this was covered elsewhere
