### ISSUE TITLE
Define jsonpath files

### ISSUE THREAD

**Issue by natilivni** [snowplow/snowplow-actionscript3-tracker#8]
I am unclear what we need to do here.  @yalisassoon referenced the link https://github.com/snowplow/example-event-dictionary.  What exactly do we need to do here?

**Comment by alexanderdean** [comment]
This is done - the file is here: https://github.com/snowplow/snowplow/blob/feature/as-support/4-storage/redshift-storage/jsonpaths/com.snowplowanalytics.snowplow/flash_context_1.json
