### ISSUE TITLE
S3 bucket names for events

### ISSUE THREAD

**Issue by natilivni** [snowplow/snowplow-actionscript3-tracker#9]
We are trying to verify the tracking events are getting through.  Which S3 bucket should they end up in?  Which bucket contains failed events?

**Comment by yalisassoon** [comment]
Data that fails the initial enrichment step will end up here:
s3://snowplow-saas-data-eu-west-1/astracker/enriched/bad.

Data that fails the shred step will end up here:
s3://snowplow-saas-data-eu-west-1/astracker/shredded/bad.

You should have access to both via the creds I shared on passpack - let me
know if you have any difficulties accessing those locations.

On Wed, Jan 14, 2015 at 9:55 AM, Netanel Livni <notifications@github.com>
wrote:

> We are trying to verify the tracking events are getting through. Which S3
> bucket should they end up in? Which bucket contains failed events?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-actionscript3-tracker/issues/9>.
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by natilivni** [comment]
The credentials are not working for snowplow-saas-data-eu-west-1

**Comment by alexanderdean** [comment]
Guys please discuss private buckets over email not public GitHub...
